# Generated by Django 2.2 on 2020-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
