# Generated by Django 2.2 on 2020-03-27 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0002_orderitem_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
    ]
